sample_app/config/routes.rb
Rails.application.routes.draw do
  resources :users
  root 'static_pages#home'

  get '/home',      to: 'static_pages#home'
  get '/help',      to: 'static_pages#help'
  get '/about',     to: 'static_pages#about'
  get '/contact',   to: 'static_pages#contact'

  get '/signup',    to: 'users#new'

  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  get '/logout',    to: 'sessions#destroy'
  # delete "/logout", to: "sessions#destroy"

  resources :account_activations,     only: :edit
  resources :password_resets,         only: %i[new edit create update]
  resources :microposts,              only: %i[create destroy]
end

sample_app/app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
         The <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a> by <a href="https://www.rasheedstarlet.com/">Rasheed Starlet</a>
    </small>
    <nav>
        <ul>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact", contact_path  %></li>
            <li><a href="https://x.com/rasheedstarlet">Twitter</a></li>
        </ul>
    </nav>
</footer>

sample_app/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<div class="container">
<%= link_to "Starlet In", home_path, id: "logo" %>
    <nav>
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>

        <ul class="nav navbar-nav navbar-right collapse navbar-collapse" id="bs-example-navbar-collapse-1">

            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Help", help_path %></li>
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Log out", logout_path, method: :delete %></li>

            <% if logged_in? %>
                <li><%= link_to "Users", '#' %></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Account <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><%= link_to "Profile", current_user %></li>
                        <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                        <li class="divider"></li>
                        <li><%= link_to "Log out", logout_path, method: :delete %></li>
                    </ul>
                </li>
            <% else %>
                <li><%= link_to "Log in", login_path %></li>
                <li><%= link_to "Sign up", signup_path %></li>
            <% end %>

        </ul>
    </nav>
</div>
</header>

sample_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= PageTitle(yield(:title)) %> </title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
      <%= render "layouts/header" %>

      <div class="container">
          <% flash.each do |message_type, message| %>
              <div class="alert alert-<%= message_type %>">
                  <%= message %>
              </div>
          <% end %>
          <%= yield %>
      </div>

      <div class="container">
        <%= render "layouts/footer" %>
        <%= debug(params) if Rails.env.development? %>
      </div>

  </body>
</html>